apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-demo-app
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: argo-jit-rbac
rules:
  # Права для деплоя demo приложения
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: [""]
    resources:
      - services
      - configmaps
      - pods
      - events
    verbs: ["create", "update", "patch", "get", "list", "watch", "delete"]
  
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "list", "watch"]