apiVersion: batch/v1
kind: CronJob
metadata:
  name: argocd-jit-rbac-cleanup
  namespace: kube-system
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 300
      template:
        metadata:
          labels:
            app.kubernetes.io/part-of: argo-jit-rbac-cleanup
        spec:
          serviceAccountName: argocd-manager
          restartPolicy: Never
          containers:
          - name: cleanup
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-c"]
            args:
              - |
                set -euo pipefail
                NOW=$(date +%s)
                COUNT_COMPLETED=0
                COUNT_TIMEOUT=0
                COUNT_ACTIVE=0
                
                echo "========================================="
                echo "JIT RBAC Cleanup started at $(date -u +%FT%TZ)"
                echo "========================================="
                
                # Event: Scan started
                kubectl create event jit-rbac-scan-started-$(date +%s) \
                  --type=Normal \
                  --reason=JitRbacScanStarted \
                  --message="action=scan status=started timestamp=$(date -u +%FT%TZ)" \
                  --reporting-controller=jit-rbac-cleanup \
                  --reporting-instance=${HOSTNAME} \
                  --namespace=kube-system || true
                
                # ========================================
                # Приоритет 1: Удалить completed
                # ========================================
                echo "--- Phase 1: Cleanup completed RBAC ---"
                kubectl get clusterrolebinding -l app.kubernetes.io/part-of=argo-jit-rbac,jit-rbac/sync-status=completed \
                  -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.metadata.labels.jit-rbac/app}{"\t"}{.roleRef.name}{"\n"}{end}' 2>/dev/null | \
                while IFS=$'\t' read -r crb_name app_name role_name; do
                  [ -z "$crb_name" ] && continue
                  
                  echo "Removing completed: CRB=$crb_name, App=$app_name, Role=$role_name"
                  
                  # Event: Cleanup completed
                  kubectl create event "jit-rbac-cleanup-${crb_name}-$(date +%s)" \
                    --type=Normal \
                    --reason=JitRbacCleanupCompleted \
                    --message="action=cleanup status=completed crb=${crb_name} app=${app_name} role=${role_name} reason=sync_completed" \
                    --reporting-controller=jit-rbac-cleanup \
                    --namespace=kube-system || true
                  
                  # Очистить rules в ClusterRole
                  kubectl patch clusterrole "$role_name" --type=merge -p '{"rules":[]}' 2>/dev/null || true
                  
                  # Удалить ClusterRoleBinding
                  kubectl delete clusterrolebinding "$crb_name" --ignore-not-found=true || true
                  
                  COUNT_COMPLETED=$((COUNT_COMPLETED + 1))
                done
                
                # ========================================
                # Приоритет 2: Удалить in-progress старше 30 минут
                # ========================================
                echo "--- Phase 2: Cleanup stuck in-progress RBAC (>30 min) ---"
                kubectl get clusterrolebinding -l app.kubernetes.io/part-of=argo-jit-rbac \
                  -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.metadata.creationTimestamp}{"\t"}{.metadata.labels.jit-rbac/sync-status}{"\t"}{.metadata.labels.jit-rbac/app}{"\t"}{.roleRef.name}{"\n"}{end}' 2>/dev/null | \
                while IFS=$'\t' read -r crb_name created status app_name role_name; do
                  [ -z "$crb_name" ] && continue
                  [ "$status" = "completed" ] && continue
                  
                  # Вычислить возраст в минутах
                  CREATED_EPOCH=$(date -d "$created" +%s 2>/dev/null || echo 0)
                  [ "$CREATED_EPOCH" = "0" ] && continue
                  AGE_MIN=$(( (NOW - CREATED_EPOCH) / 60 ))
                  
                  if [ "$status" = "in-progress" ]; then
                    if [ $AGE_MIN -gt 30 ]; then
                      echo "Removing stuck in-progress: CRB=$crb_name, App=$app_name, Age=${AGE_MIN}m"
                      
                      # Event: Cleanup timeout
                      kubectl create event "jit-rbac-timeout-${crb_name}-$(date +%s)" \
                        --type=Warning \
                        --reason=JitRbacCleanupTimeout \
                        --message="action=cleanup status=timeout crb=${crb_name} app=${app_name} role=${role_name} age_min=${AGE_MIN} reason=stuck" \
                        --reporting-controller=jit-rbac-cleanup \
                        --namespace=kube-system || true
                      
                      # Очистить rules
                      kubectl patch clusterrole "$role_name" --type=merge -p '{"rules":[]}' 2>/dev/null || true
                      
                      # Удалить CRB
                      kubectl delete clusterrolebinding "$crb_name" --ignore-not-found=true || true
                      
                      COUNT_TIMEOUT=$((COUNT_TIMEOUT + 1))
                    else
                      COUNT_ACTIVE=$((COUNT_ACTIVE + 1))
                    fi
                  fi
                done
                
                # ========================================
                # Cleanup succeeded pods
                # ========================================
                echo "--- Phase 3: Cleanup succeeded pods ---"
                kubectl delete pod -n kube-system \
                  -l app.kubernetes.io/part-of=argo-jit-rbac \
                  --field-selector=status.phase=Succeeded \
                  --ignore-not-found=true 2>/dev/null || true
                
                # ========================================
                # Final statistics
                # ========================================
                echo "========================================="
                echo "Summary:"
                echo "  Removed completed: $COUNT_COMPLETED"
                echo "  Removed timeout:   $COUNT_TIMEOUT"
                echo "  Active in-progress: $COUNT_ACTIVE"
                echo "JIT RBAC Cleanup completed at $(date -u +%FT%TZ)"
                echo "========================================="
                
                # Event: Scan completed
                kubectl create event jit-rbac-scan-completed-$(date +%s) \
                  --type=Normal \
                  --reason=JitRbacScanCompleted \
                  --message="action=scan status=completed removed_completed=${COUNT_COMPLETED} removed_timeout=${COUNT_TIMEOUT} active_in_progress=${COUNT_ACTIVE} timestamp=$(date -u +%FT%TZ)" \
                  --reporting-controller=jit-rbac-cleanup \
                  --reporting-instance=${HOSTNAME} \
                  --namespace=kube-system || true