apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kind-spoke1-demo
  namespace: argocd
spec:
  project: default
  destination:
    name: kind-spoke1
    namespace: demo-spoke1
  sources:
    # Source 1: JIT RBAC шаблон (wave -1)
    - repoURL: 'https://github.com/kepler010101/arg.git'
      targetRevision: main
      path: shared/jit-rbac
      kustomize:
        commonLabels:
          jit-rbac/app: kind-spoke1-demo
        patches:
          - target:
              kind: ClusterRole
            patch: |-
              - op: replace
                path: /metadata/name
                value: argocd-manager-demo-app
          - target:
              kind: ClusterRoleBinding
            patch: |-
              - op: replace
                path: /metadata/name
                value: argocd-manager-demo-app
              - op: replace
                path: /roleRef/name
                value: argocd-manager-demo-app
          - target:
              kind: Job
            patch: |-
              - op: replace
                path: /metadata/name
                value: kind-spoke1-demo-mark-completed
    
    # Source 2: Роль с правами (wave 0)
    - repoURL: 'https://github.com/kepler010101/arg.git'
      targetRevision: main
      path: shared/jit-rbac-roles
      directory:
        include: demo-app-role.yaml
    
    # Source 3: Само приложение (wave 1+)
    - repoURL: 'https://github.com/kepler010101/arg.git'
      targetRevision: main
      path: apps/demo
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true